<div class="row" style="max-width: 895px;">
    <div class="col-xs-10 col-md-6">
      <? foreach ($this->dados['imagens'] as $key=>$row){?>
        <a class="fancybox" rel="group" href="<?=$this->BaseUrl('imagens/vendas/'.$row['imagem']); ?>">
            <img class="ImgGalery" src="<?= $this->Img('imagens/vendas/'.$row['imagem'], 200, 200); ?>" alt="<?=$this->dados['nome']. ' - '.($key+1);?>">
        </a>
      <? }?>
    </div>
    <div class="col-xs-8 col-md-6">
        <div class="list-group">
        <a href="#" class="list-group-item disabled">
        <?=$this->dados['nome'];?>
        </a>
        <? if(!empty($this->dados['nome_categoria'])){?>
            <a href="#" class="list-group-item">Categoria: <?=$this->dados['nome_categoria'];?></a>
        <? }?>
        
        <? if(!empty($this->dados['valor'])){?>
            <a href="#" class="list-group-item">Valor: R$ <?=number_format($this->dados['valor'], 2, ".", ",");?></a>
        <? }else{?>
            <a href="#" class="list-group-item">Valor: a negociar</a> 
        <? }?>
        
       
        <? if(!empty($this->dados['descricao'])){?>
            <a href="#" class="list-group-item">Descrição:<?=$this->dados['descricao'];?></a>
        <? }?>
       
        </div> 
    </div>    
</div>