<?
$this->headScript()->appendFile($this->BaseUrl('assets/js/vendas.js'));
?>
<div class="row">
   <div class="col-md-3">
      <p class="lead lista-categoria">Categorias</p>
      <div class="list-group">
<!--        <a href="#" class="list-group-item categoria" data-param="0">Todas</a>-->
        <? foreach($this->categorias as $categoria){ ?> 
          <a href="#" class="list-group-item categoria" data-param="<?=$categoria['id'];?>"><?= ucfirst($categoria['nome']);?></a>
        <? } ?> 
      </div>
   </div>
   <div class="col-md-9">
     <div class="row vendas">
        <? if($this->vendas){ 
            foreach($this->vendas as $venda){
        ?>
         <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
               <div class="img-venda" style="background-image: url(<?= $this->BaseUrl('/imagens/vendas/' . $venda['imagem']); ?>);"></div>
               <div class="caption">
                   <h4 class="pull-right" style="color: red;"><? 
                   if(!empty($venda['valor'])){ 
                    echo 'R$ '. number_format($venda['valor'], 2, ".", ",");
                   
                   }else{
                       echo 'A negociar';
                   }
                    ?>
                   </h4>
                  <h4><a href="#"><?=$venda['nome'];?></a>
                  </h4>
                   <div style="margin: 0 0 0px">
                        <?=$venda['descricao'];?>
                   </div>
               </div>
               <div class="alert clearfix">
                  <button type="button" class="btn btn-success pull-right venda" data-id="<?=$venda['id'];?>">Visualizar</button>    
               </div>
            </div>
         </div>
        <? } }?>  
               
      </div>
   </div>
</div>