<?php $controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName(); ?>
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
   <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->     
      <div class="navbar-header">         
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">         
         <span class="sr-only">Toggle navigation</span>         
         <span class="icon-bar"></span>         
         <span class="icon-bar"></span>        
         <span class="icon-bar"></span>         
          </button>          
         <img src="<?= $this->BaseUrl('assets/images/logo.png'); ?>" alt="Smiley face" style="width: 160px;margin-right: 28px;margin-top: 8px;">      
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->      
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
         <ul class="nav navbar-nav">
            <li>               
                <a href="<?= $this->url(array('controller' => 'index'), 'default', TRUE); ?>"><i class="glyphicon glyphicon-home"></i> Inicio</a>            
            </li>
            <li>               
                <a href="<?= $this->url(array('controller' => 'carrinho'), 'default', TRUE); ?>"><i class="glyphicon glyphicon-check"></i> Carrinho</a>            
            </li>
            <li>               <
                <a href="<?= $this->url(array('controller' => 'cadastro'), 'default', TRUE); ?>"><i class="glyphicon glyphicon-copy"></i> Cadastra-se</a>            
            </li>
         </ul>
         <ul class="nav navbar-top-links navbar-right">
            <li class="dropdown">
               <? if ($this->login->id) { ?>                    
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="color: #FFF; top: 12px;">                        
                   <i class="glyphicon glyphicon-user"></i> Minha Conta                    
                </a>                                        <!-- dropdown user-->                    
               <ul class="dropdown-menu dropdown-user">
                  <li>
                      <a href="<?= $this->url(array('controller' => 'minha-conta', 'action' => 'pedidos'), 'default', TRUE); ?>"><i class="fa fa-user fa-fw"></i> Meus Pedidos</a>
                  </li>
                  <li>
                      <a href="<?= $this->url(array('controller' => 'minha-conta', 'action' => 'meus-dados'), 'default', TRUE); ?>"><i class="fa fa-gear fa-fw"></i>Meus Dados</a>                        
                  </li>
                  <li class="divider"></li>
                  <li>
                      <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'minha-conta', 'action' => 'logout'), null, true); ?>"><i class="fa fa-sign-out fa-fw"></i>Sair</a>                        
                  </li>
               </ul>
               <!-- end dropdown-user -->                    
               <? } else { ?>                        
               <a class="dropdown-toggle"  href="<?= $this->url(array('controller' => 'minha-conta', 'action' => 'acesso'), 'default', TRUE); ?>" style="color: #FFF; top: 5px;">                            
                   <i class="glyphicon glyphicon-user"></i> Minha Conta                        
               </a>                    
               <? } ?>                
            </li>
            <!-- end main dropdown -->            
         </ul>
      </div>
      <!-- /.navbar-collapse -->   
   </div>
   <!-- /.container -->
</nav>