<?
$this->headScript()->appendFile($this->BaseUrl('assets/js/cadastro.js'));
$this->headScript()->appendFile($this->BaseUrl('assets/js/meus-dados.js'));
?>
<div class="container">
   <h1 class="well">Seus Dados</h1>
   <?=$this->FlashMessenger(); ?>
   <div class="col-lg-12 well">
      <div class="row">
          <form id="cadastro" enctype="multipart/form-data" method="POST" action="<?php echo $this->url(array('module' => 'default', 'controller' => 'minha-conta', 'action'=>'meus-dados'), null, true); ?>">
            <div class="col-sm-12">
               <div class="row">
                   
                   <?
                   if($this->dados['tipo_pessoa']==1){
                       $label_nome ='Nome';
                       $placeholder_nome ='Insira seu Nome';
                       $label_sobrenome ='Sobrenome';
                       $placeholder_sobrenome ='Insira seu Sobrenome';
                       $label_doc1 ='CPF';
                       $placeholder_doc1 ='Insira seu CPF';
                        $label_doc2 ='RG';
                       $placeholder_doc2 ='Insira seu RG';
                       
                   }else{
                       $label_nome ='Razão Social';
                       $placeholder_nome ='Insira a Razão Social';
                       $label_sobrenome ='Nome Fantasia';
                       $placeholder_sobrenome ='Insira o Nome Fantasia';
                       $label_doc1 ='CNPJ';
                       $placeholder_doc1 ='Insira o CNPJ';
                       $label_doc2 ='I.E';
                       $placeholder_doc2 ='Insira a Inscrição Estadual';
                   }
                   
                   ?>
                <div class="col-sm-6 form-group">
                      <label id="label-nome1"><?=$label_nome;?></label>
                     <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input name="id" id="id" value="<?=$this->dados['id'];?>" type="hidden">
                        <input name="nome1" id="noem1" placeholder="<?=$placeholder_nome;?>" required="required" value="<?=$this->dados['nome1'];?>" class="form-control"  type="text">
                     </div>
                  </div>
                  <div class="col-sm-6 form-group">
                     <label id="label-nome2"><?=$label_sobrenome?></label>
                     <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input name="nome2" id="nome2" placeholder="<?=$placeholder_sobrenome;?>" required="required" value="<?=$this->dados['nome2'];?>" class="form-control"  type="text">
                     </div>
                  </div>
                   
                   <div class="col-sm-6 form-group">
                     <label id="label-doc1"><?=$label_doc1;?></label>
                     <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-list-alt"></i></span>
                        <input name="doc1" id="doc1" placeholder="<?=$placeholder_doc1;?>" class="form-control cpfOuCnpj" required="required" value="<?=$this->dados['doc1'];?>" type="text">
                     </div>
                  </div>
                  <div class="col-sm-6 form-group">
                     <label id="label-doc2"><?=$label_doc2;?></label>
                     <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-list-alt"></i></span>
                        <input name="doc2" id="doc2" placeholder="<?=$placeholder_doc2;?>" class="form-control" required="required" value="<?=$this->dados['doc2'];?>" type="text">
                     </div>
                  </div>
               </div>
              
               <div class="row">
                   
                   <div class="col-sm-4 form-group">
                     <label>CEP</label>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-certificate"></i></span>
                        <input name="cep" id="cep" placeholder="Insira seu CEP" value="<?=$this->dados['cep'];?>" class="form-control"  type="text">
                     </div>
                  </div>
                   
                  <div class="col-sm-8 form-group">
                     <label>Endereço</label>
                     <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
                        <input name="endereco" required="required" placeholder="Insira seu Endereço" value="<?=$this->dados['endereco'];?>" class="form-control"  type="text">
                     </div>
                  </div>
                  <div class="col-sm-4 form-group">
                     <label>Bairro</label>
                     <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-ok"></i></span>
                        <input name="bairro" required="required" placeholder="Insira seu Bairro" value="<?=$this->dados['bairro'];?>" class="form-control"  type="text">
                     </div>
                  </div>
                   
                  <div class="col-sm-4 form-group">
                     <label>Cidade</label>
                     <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
                        <input name="cidade" required="required" placeholder="Insira sua cidade" value="<?=$this->dados['cidade'];?>" class="form-control"  type="text">
                     </div>
                  </div>
                  <div class="col-sm-4 form-group">
                     <label>Estado</label>
                     <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-ok"></i></span>
                        <input name="estado" required="required" placeholder="Insira seu estado" value="<?=$this->dados['estado'];?>" class="form-control"  type="text">
                     </div>
                  </div>
                  
               </div>
              
               <div class="col-sm-6 form-group">
                  <label>Telefone</label>
                  <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-phone-alt"></i></span>
                        <input name="telefone" id="telefone" placeholder="Insira seu telefone" value="<?=$this->dados['telefone'];?>" class="form-control" required="required" type="text">
                  </div>
               </div>
               <div class="col-sm-6 form-group">
                  <label>Email</label>
                  <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                        <input name="email" placeholder="Insira seu email" value="<?=$this->dados['email'];?>" class="form-control"  type="email">
                  </div>
               </div>
                
                <div class="col-sm-6 form-group">
                  <label>Senha</label>
                  <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-king"></i></span>
                        <input name="senha"  id="senha"  placeholder="********" class="form-control"  type="password">
                  </div>
               </div>
                
                
                <div class="col-sm-6 form-group">
                  <label>Confirmação de Senha</label>
                  <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-king"></i></span>
                        <input name="confirma_senha" id="confirma_senha"  placeholder="********" class="form-control"  type="password">
                  </div>
               </div>
                <button type="button" class="btn btn-lg btn-primary editar">Editar</button>
                <button type="submit" disabled class="btn btn-lg btn-success salvar">Salvar</button>					
            </div>
         </form>
      </div>
   </div>
</div>